# This task is for Linux only.
if(LITE)
  if(Transports.MobileInternet)
    set(TASK_ENABLED TRUE)
    if(NOT DUNE_OS_LINUX)
      set(TASK_ENABLED FALSE)
    endif(NOT DUNE_OS_LINUX)
  else(Transports.MobileInternet)
    set(TASK_ENABLED FALSE)
  endif(Transports.MobileInternet)
else(LITE)
  if(NOT DUNE_OS_LINUX)
    set(TASK_ENABLED FALSE)
  endif(NOT DUNE_OS_LINUX)
endif(LITE)
