# This task is not compatible with IMC v5.x
if(LITE)
  if(Maneuver.FollowTarget)
    set(TASK_ENABLED TRUE)
    message(STATUS "${Yellow}Maneuver.FollowTarget: This task is not compatible with IMC v5.x${ColourReset}")
  else(Maneuver.FollowTarget)
    set(TASK_ENABLED FALSE)
  endif(Maneuver.FollowTarget)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
