if(LITE)
  if(Maneuver.VehicleFormation.Test)
    set(TASK_ENABLED TRUE)
  else(Maneuver.VehicleFormation.Test)
    set(TASK_ENABLED FALSE)
  endif(Maneuver.VehicleFormation.Test)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
