if(LITE)
  if(VehicleFormation.Test)
    set(TASK_ENABLED TRUE)
  else(TVehicleFormation.Test)
    set(TASK_ENABLED FALSE)
  endif(VehicleFormation.Test)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
