if(LITE)
  if(VehicleFormation.Coordinator)
    set(TASK_ENABLED TRUE)
  else(TVehicleFormation.Coordinator)
    set(TASK_ENABLED FALSE)
  endif(VehicleFormation.Coordinator)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
