if(LITE)
  if(Maneuver.VehicleFormation.Coordinator)
    set(TASK_ENABLED TRUE)
  else(Maneuver.VehicleFormation.Coordinator)
    set(TASK_ENABLED FALSE)
  endif(Maneuver.VehicleFormation.Coordinator)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
