# This task is not compatible with IMC v5.x
if(LITE)
  if(Maneuver.FlyByCamera)
    set(TASK_ENABLED TRUE)
    message(STATUS "${Yellow}Maneuver.FlyByCamera: This task is not compatible with IMC v5.x${ColourReset}")
  else(Maneuver.FlyByCamera)
    set(TASK_ENABLED FALSE)
  endif(Maneuver.FlyByCamera)
else(LITE)
  set(TASK_ENABLED FALSE)
endif(LITE)
