##    Actuatores
SET(AMC FALSE)
SET(Broom FALSE)
SET(FLIRPTU FALSE)
SET(LED4R FALSE)
SET(MCD4R FALSE)
SET(MicroCamD FALSE)
SET(PWM FALSE)
SET(SCRTv4 FALSE)
SET(SIMCT01 FALSE)
SET(SingleSIMCT01 FALSE)

##    Autonomy
SET(OnEvent FALSE)
SET(TextActions FALSE)
SET(TREX FALSE)

## Color CMAKE Output
if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()