set(TASK_LICENSE "Proprietary")
if(LITE)
  if(Navigation.General.LBL)
    set(TASK_ENABLED TRUE)
  else(Navigation.General.LBL)
    set(TASK_ENABLED FALSE)
  endif(Navigation.General.LBL)
endif(LITE)
