# This task is not compatible with IMC v5.x
if(LITE)
  if(Maneuver.CoverArea)
    set(TASK_ENABLED TRUE)
    message(STATUS "${Yellow}Maneuver.CoverArea: This task is not compatible with IMC v5.x${ColourReset}")
  else(Maneuver.CoverArea)
    set(TASK_ENABLED FALSE)
  endif(Maneuver.CoverArea)
else(LITE)
  set(TASK_ENABLED TRUE)
endif(LITE)
